name: Deploy to GitHub Repo

on:
  push:
    branches:
      - main

jobs:
  deploy_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read and parse environment variables
        run: |
          export ENV_VARS=$(cats scripts/config.json)
          echo "::set-env name=ENV_VARS::$ENV_VARS"

      - name: Run deploy script
        run: |
          bash scripts/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO_NAME: ${{ fromJSON(env.ENV_VARS).REPO_NAME }}
          DESCRIPTION: ${{ fromJSON(env.ENV_VARS).DESCRIPTION }}
          DELETE_REPO: ${{ fromJSON(env.ENV_VARS).DELETE_REPO }}

      - name: Copy Folder
        run: | 
          cd $REPO_NAME 
          cp -r ../template/* ../$REPO_NAME
          git add .
          git commit -m "Copy folder to repository"
          git push origin main  # Change 'main' to the target branch

      - name: Install Helm Plugins
        run: |
          helm plugin install https://github.com/databus23/helm-diff
