name: Create GitHub Repo

on:
  push:
    branches:
      - main

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script to create GitHub repo
        run: |
          bash scripts/create_repo.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
