name: Deploy to GitHub Repo

on:
  push:
    branches:
      - main

jobs:
  deploy_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deploy script
        run: |
          bash scripts/deploy.sh
        env:
          GITHUB_TOKEN: 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
