name: Deploy to GitHub Repo

on:
  push:
    branches:
      - main

jobs:
  deploy_repo:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: owldq-dev-05
      DESCRIPTION: Your repository description
      PRIVATE: false
      INITIALIZE_README: true
      DELETE_REPO: false  # Set to true if you want to delete the repository 
      HELMFILE_PATH: ./helmfile.yaml
      CHARTS_PATH: ./helmcharts
      REPO_URL: https://raw.githubusercontent.com/$USERNAME/$REPO_NAME/main/helmcharts

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deploy script
        run: |
          bash scripts/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO_NAME: ${{ env.REPO_NAME }}
          DESCRIPTION: ${{ env.DESCRIPTION }}
          DELETE_REPO: ${{ env.DELETE_REPO }}

      - name: Copy Folder
        run: | 
          cd $REPO_NAME 
          cp -r ../template/* ../$REPO_NAME
          git add .
          git commit -m "Copy folder to repository"
          git push origin main  # Change 'main' to the target branch

      - name: Install Helm Plugins
        run: |
          helm plugin install https://github.com/databus23/helm-diff

      - name: Index Helm Charts
        run: |
          helm repo index $CHARTS_PATH --url $REPO_NAME
      
      - name: Deploy with Helmfile
        run: |
          helmfile --file $HELMFILE_PATH apply

      
      
